### ISSUE TITLE
not work for integer

### ISSUE THREAD

**Issue by artempartos** [kaize/valle#22]
Hi! I am add valle with default config, not set any options. 
Then i use my model Realty and do next commands in rails console
```ruby
r = Realty.last
r.lot = 123123123123123
r.save
```
and get 
```ruby
ActiveRecord::StatementInvalid: PG::Error: ERROR:  integer out of range
: UPDATE "realty" SET "lot" = 123123123123123, "updated_at" = '2015-05-28 15:13:16.308810' WHERE "realty"."id" = 1028
from /home/vagrant/.rvm/gems/ruby-2.1.5/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `exec'
```
But other valle validations are work (string for example)
```ruby
r.legacy_geo = "a" * 300
r.valid? => false
r.errors.messages
=> {:legacy_geo=>
  ["слишком большой длины (не может быть больше чем 255 символов)"]
```
lot - integer, legacy_geo - string
```
create_table "realty", :force => true do |t|
    t.integer  "lot",  :null => false
    t.string   "legacy_geo"
end
```
Rails 3.2.21
What i am doing wrong?

**Comment by akalyaev** [comment]
Unfortunately, valle won't work without `limit` option. What does it mean?

When you define your column like that:

```
t.integer  "lot",  :null => false
```

there is no easy way to detect the size of integer (it will be limited in database, but AR won't have any clue about that fact)

So, in order valle to work, you need to explicitly set limit for your column (so AR know it):

```
t.integer  "lot",  :null => false, :limit => 4
```

4 means 4 bytes. Docs - http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column
