### ISSUE TITLE
Valle doesn't work in Rails with configuration option "cache_classes" switched on. In other words, in typical non development environments.

### ISSUE THREAD

**Issue by alexpetrov** [kaize/valle#23]
In any typical non development Rails enviornments, when `config.chache_classes=true` valle doesn't work.
Seems like there are some issues with the order of class loading.

There is the same issue, but with less details: https://github.com/kaize/valle/issues/21

To reproduce it, try to make a test in rails app witj `config.cache_classes=true

**Comment by dapi** [comment]
+1

**Comment by dapi** [comment]
here is quick fix - https://github.com/kaize/valle/issues/21#issuecomment-197300838

**Comment by akalyaev** [comment]
Should be working now.
